name: update_tvl
on:
    workflow_dispatch:
        inputs:
            slug:
                description: "Defiliama protocol slug. If 'all' refreshes all protocols"
                required: true
    schedule:
        # Runs daily at 9:25 AM UTC (4:25 AM EST)
        # Odd time used to avoid conflicts with other workflows
        - cron: "25 9 * * *"

jobs:
    update_tvl:
        runs-on: ubuntu-latest
        name: "Update TVL: ${{ github.event.inputs.slug || 'all' }}"

        steps:
            - uses: actions/checkout@v4

            - uses: ./.github/actions/load-sops-secrets
              with:
                age_key: ${{ secrets.SOPS_AGE_KEY }}

            - uses: actions/setup-go@v5
              with:
                  go-version: 1.22.3
                  cache: true

            - run: go mod download

            - run: go build -o main cmd/main/main.go

            - name: Run the program
              run: |
                  ./main refresh-tvl \
                    --slug=${{ github.event.inputs.slug || 'all' }} \
                    --prod=true